from .administrator import AdministratorView  # noqa: F401
from .administrator import dashboard  # noqa: F401
from .administrator import LoginView  # noqa: F401
from .administrator import LogoutView  # noqa: F401
from .administrator import SignUpView  # noqa: F401
from .dish import DishDeleteView  # noqa: F401
from .dish import DishListView  # noqa: F401
from .dish import DishUpdateView  # noqa: F401
from .dish_review import DishReviewCreateView  # noqa: F401
from .dish_review import DishReviewDeleteView  # noqa: F401
from .dish_review import DishReviewListView  # noqa: F401
from .driver import DriverDeleteView  # noqa: F401
from .driver import DriverListView  # noqa: F401
from .driver import DriverUpdateView  # noqa: F401
