# Generated by Django 5.0.1 on 2024-02-08 13:14
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_dishreview_stars"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="dish",
        ),
        migrations.RemoveField(
            model_name="dishreview",
            name="email",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="location",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="vehicle",
        ),
        migrations.CreateModel(
            name="DriverReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("stars", models.IntegerField()),
                ("review", models.TextField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.driver",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
