# Generated by Django 5.0.1 on 2024-02-08 14:48
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_remove_orderitem_order_remove_orderitem_dish_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="price",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="email",
        ),
        migrations.RemoveField(
            model_name="driverreview",
            name="email",
        ),
        migrations.RemoveField(
            model_name="driverreview",
            name="stars",
        ),
        migrations.AddField(
            model_name="driver",
            name="image",
            field=models.ImageField(default=None, upload_to="drivers/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dishreview",
            name="stars",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
