# Generated by Django 5.0.1 on 2024-02-08 14:51
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_remove_dish_price_remove_driver_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=25,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
            preserve_default=False,
        ),
    ]
